# Generated by Django 2.1.7 on 2019-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('cif', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('tlf', models.IntegerField(max_length=9)),
                ('fax', models.IntegerField(max_length=9)),
                ('url', models.URLField(max_length=40)),
                ('email', models.EmailField(max_length=35)),
                ('activo', models.BooleanField()),
                ('fecha_alta', models.DateField()),
                ('numero_trabajadores', models.IntegerField()),
            ],
        ),
    ]
