# Generated by Django 2.1.7 on 2019-02-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(default="1999-01-01"),
        ),
    ]
