# Generated by Django 2.1.7 on 2019-02-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_cliente_fecha_alta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineafactura',
            old_name='unidades',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='lineafactura',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='articulo',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='curso.Factura'),
        ),
    ]
