# Generated by Django 2.1.7 on 2019-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20190220_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=120)),
                ('asunto', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('texto', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
